/**
 * One worked example of an item type, with the answer shown.
 *
 * These are generated by exactly the same code that generates the test, from a
 * fixed seed. That is the cheap part of scope §12: a page explaining every
 * question type with real examples costs nothing to build and cannot be copied
 * at volume by anyone without the generator.
 *
 * Server-rendered, so it needs no JavaScript and it is in the HTML a search
 * engine reads.
 */

import { generateItem, type Level, type ReasoningItemType } from '@/lib/reasoning/generate'
import { FigureCell, StimulusView } from './Figures'

export function WorkedExample({
  type,
  level,
  seed,
}: {
  type: ReasoningItemType
  level: Level
  seed: string
}) {
  const item = generateItem(type, level, seed)
  const prefix = `ex-${type}-${seed}`

  return (
    <div className="rounded-2xl border border-black/5 bg-surface p-4">
      <p className="mb-3 text-[15px] font-semibold text-ink">{item.prompt}</p>

      {item.stimulus.kind !== 'odd_one_out' && (
        <div className="mb-4">
          <StimulusView stimulus={item.stimulus} idPrefix={prefix} />
        </div>
      )}

      <p className="mb-2 font-mono text-xs uppercase tracking-wider text-ink-2">
        {item.stimulus.kind === 'odd_one_out' ? 'The five shapes' : 'The choices'}
      </p>
      {/* Same sizing rule as the live runner: two or three across on a phone,
          because a 55px figure cannot show a rotation. */}
      <ul
        className={`grid list-none gap-3 ${
          item.options.length === 5
            ? 'grid-cols-3 sm:grid-cols-5'
            : 'grid-cols-2 sm:grid-cols-4'
        }`}
      >
        {item.options.map((figure, i) => {
          const isAnswer = i === item.correctIndex
          return (
            <li key={i}>
              <FigureCell
                figure={figure}
                idPrefix={`${prefix}-o${i}`}
                className={isAnswer ? 'border-2 border-success' : ''}
              />
              {/* Named, not just coloured. The whole product bans colour-only
                  cues, and this page in particular is read by people checking
                  whether the test is fair. */}
              <span
                className={`mt-1 block text-center font-mono text-[11px] ${
                  isAnswer ? 'font-bold text-success' : 'text-ink-2'
                }`}
              >
                {isAnswer ? 'Answer' : i + 1}
              </span>
            </li>
          )
        })}
      </ul>
    </div>
  )
}
