-- Phase 2 — auth bridge, seeds, and Row Level Security.
-- Source of truth: CLAUDE.md §3, §7, §8, §10 (zone names), §14 Phase 2.
--
-- This migration is hand-authored. It runs AFTER 20260520120000_phase2_foundation/migration.sql,
-- which Prisma generated by diffing prisma/schema.prisma against an empty database.
--
-- This file does four things in order:
--   1. Bridge `profiles.user_id` to Supabase's `auth.users` (FK + cascade delete for GDPR).
--   2. Enforce CLAUDE.md §3: child profiles must have a year_group_id.
--   3. Seed year_groups (Year 3 / Year 7), subjects (Maths / English / Science), zones (CLAUDE.md §10).
--   4. Install a SECURITY DEFINER trigger on auth.users so registration automatically creates
--      the matching profiles row, resolving year_group label → id.
--   5. Enable RLS and install fail-closed policies for the Phase 2 surface area: profiles,
--      family_links, parent_controls, year_groups, subjects, zones, plus baseline published-only
--      read policies for content tables (quiz_questions, card_catalog, learn_content).
--
-- Phases beyond Phase 2 will tighten policies further (e.g. attempts/answers writes).
-- For Phase 2 the rule is: anything not explicitly granted is denied.

-- =========================================================================
-- 1. auth.users bridge
-- =========================================================================

-- profiles.user_id references auth.users.id. ON DELETE CASCADE so a Supabase
-- account deletion (Phase 9 GDPR delete) wipes the application profile in one step.
ALTER TABLE "profiles"
  ADD CONSTRAINT "profiles_user_id_auth_users_fkey"
  FOREIGN KEY ("user_id")
  REFERENCES "auth"."users"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;

-- =========================================================================
-- 2. Child-must-have-year-group invariant
-- =========================================================================

-- CLAUDE.md §3: MVP is Year 3 and Year 7. A child profile without a year group
-- is meaningless; a parent profile MUST NOT have one (parents aren't pinned to a year).
ALTER TABLE "profiles"
  ADD CONSTRAINT "profiles_role_year_group_chk"
  CHECK (
    (role = 'child'  AND year_group_id IS NOT NULL) OR
    (role = 'parent' AND year_group_id IS NULL)     OR
    (role = 'admin')
  );

-- =========================================================================
-- 3. Seed reference data
-- =========================================================================

-- Year groups — MVP scope (CLAUDE.md §3, §14 Phase 2). Year 1-2 Foundation Mode
-- and Years 10-13 GCSE/A-level are deferred to §11 and must not be inserted here.
INSERT INTO "year_groups" ("label", "key_stage") VALUES
  ('year-3', 'KS2'),
  ('year-7', 'KS3')
ON CONFLICT ("label") DO NOTHING;

-- Subjects — CLAUDE.md §3 (Maths first, then English, then Science). Colour tokens
-- from CLAUDE.md §10 colour-token table (--maths, --english, --science).
INSERT INTO "subjects" ("name", "colour_token") VALUES
  ('Maths',   '#6C9EFF'),
  ('English', '#FF8FAB'),
  ('Science', '#52D9A0')
ON CONFLICT ("name") DO NOTHING;

-- Baseline zones — CLAUDE.md §10. Year 3 and Year 7 only, per MVP scope.
-- Topics are NOT seeded here — they land in Phases 3/6/11 as content is generated.
INSERT INTO "zones" ("year_group_id", "subject_id", "name", "theme")
SELECT yg.id, s.id, z.name, z.theme
FROM (
  VALUES
    ('year-3', 'Maths',   'Number Jungle',     'jungle'),
    ('year-3', 'English', 'Whispering Woods',  'woodland'),
    ('year-3', 'Science', 'Discovery Cave',    'cave'),
    ('year-7', 'Maths',   'Crystal Labyrinth', 'crystal'),
    ('year-7', 'English', 'Library of Echoes', 'library'),
    ('year-7', 'Science', 'Elemental Forge',   'forge')
) AS z(year_group_label, subject_name, name, theme)
JOIN "year_groups" yg ON yg.label = z.year_group_label
JOIN "subjects"    s  ON s.name   = z.subject_name
WHERE NOT EXISTS (
  SELECT 1 FROM "zones" existing
  WHERE existing.year_group_id = yg.id
    AND existing.subject_id    = s.id
    AND existing.name          = z.name
);

-- =========================================================================
-- 4. Registration trigger: auth.users insert → profiles insert
-- =========================================================================

-- The browser RegisterForm calls supabase.auth.signUp with role/display_name/year_group
-- in options.data. Supabase stores that on auth.users.raw_user_meta_data. This trigger
-- materialises a profiles row from that metadata so the rest of the app reads the DB,
-- not auth metadata.
--
-- SECURITY DEFINER + explicit search_path so the function runs as the trigger owner,
-- can resolve year_groups.label → id, and is safe against search_path injection.
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_role           text;
  v_display_name   text;
  v_year_label     text;
  v_year_group_id  uuid;
BEGIN
  v_role         := COALESCE(NEW.raw_user_meta_data->>'role', 'child');
  v_display_name := COALESCE(NULLIF(trim(NEW.raw_user_meta_data->>'display_name'), ''), NEW.email, 'Explorer');
  v_year_label   := NEW.raw_user_meta_data->>'year_group';

  IF v_role NOT IN ('child', 'parent', 'admin') THEN
    RAISE EXCEPTION 'handle_new_auth_user: invalid role %', v_role;
  END IF;

  IF v_role = 'child' THEN
    IF v_year_label IS NULL THEN
      RAISE EXCEPTION 'handle_new_auth_user: child registrations must include year_group metadata';
    END IF;
    SELECT id INTO v_year_group_id FROM public.year_groups WHERE label = v_year_label;
    IF v_year_group_id IS NULL THEN
      RAISE EXCEPTION 'handle_new_auth_user: unknown year_group label %', v_year_label;
    END IF;
  END IF;

  INSERT INTO public.profiles (user_id, display_name, role, year_group_id)
  VALUES (NEW.id, v_display_name, v_role::"Role", v_year_group_id)
  ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

-- =========================================================================
-- 5. Row Level Security
-- =========================================================================
--
-- Posture: fail closed. Every sensitive table has RLS enabled, no permissive
-- catch-all policies, and policies grant ONLY what CLAUDE.md §7 baseline requires.
-- The Postgres role `authenticated` is Supabase's per-user role; `service_role`
-- bypasses RLS by default and is used by trusted server code (trigger above,
-- future admin tools).
--
-- Helper: is this user an admin? Used by parent-controls and (eventually)
-- monitoring policies. SECURITY DEFINER so it can read profiles regardless of
-- the caller's RLS view.
CREATE OR REPLACE FUNCTION public.current_user_is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE user_id = auth.uid() AND role = 'admin'
  );
$$;

-- ---- profiles ----
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "profiles" FORCE ROW LEVEL SECURITY;

-- Self read
CREATE POLICY "profiles_select_self"
  ON "profiles" FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- Linked parent can read child profile
CREATE POLICY "profiles_select_linked_child"
  ON "profiles" FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.family_links fl
      WHERE fl.parent_user_id = auth.uid()
        AND fl.child_user_id  = "profiles".user_id
    )
  );

-- Admin can read all (Phase 12 monitoring; allowed now because admin role must
-- be granted out-of-band, never via self-registration — see lib/auth/roles.ts).
CREATE POLICY "profiles_select_admin"
  ON "profiles" FOR SELECT TO authenticated
  USING (public.current_user_is_admin());

-- Self update (display name, theme, study_buddy, etc.). Role and year_group_id
-- are protected: a user cannot escalate to admin or change which year-group
-- they belong to via a profiles UPDATE.
CREATE POLICY "profiles_update_self"
  ON "profiles" FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (
    user_id = auth.uid()
    AND role          = (SELECT p.role          FROM public.profiles p WHERE p.user_id = auth.uid())
    AND year_group_id IS NOT DISTINCT FROM
        (SELECT p.year_group_id FROM public.profiles p WHERE p.user_id = auth.uid())
  );

-- No INSERT policy: profile rows are created exclusively by the auth-user
-- trigger, which runs as table owner and bypasses RLS. Clients cannot insert.
-- No DELETE policy: account deletion cascades from auth.users.

-- ---- family_links ----
ALTER TABLE "family_links" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "family_links" FORCE ROW LEVEL SECURITY;

-- Parent or child can see their own links. No cross-family visibility.
CREATE POLICY "family_links_select_party"
  ON "family_links" FOR SELECT TO authenticated
  USING (parent_user_id = auth.uid() OR child_user_id = auth.uid());

CREATE POLICY "family_links_select_admin"
  ON "family_links" FOR SELECT TO authenticated
  USING (public.current_user_is_admin());

-- INSERT/UPDATE/DELETE intentionally omitted in Phase 2 — the family linking UI
-- ships in a later phase (CLAUDE.md §14 Phase 1 already created accounts; the
-- linking flow itself is owned by the parent dashboard, Phase 9). Until then,
-- links are seeded via service_role only.

-- ---- parent_controls ----
ALTER TABLE "parent_controls" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "parent_controls" FORCE ROW LEVEL SECURITY;

-- Linked parent can read/write the controls for their child.
CREATE POLICY "parent_controls_select_linked_parent"
  ON "parent_controls" FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      JOIN public.family_links fl ON fl.child_user_id = p.user_id
      WHERE p.id = "parent_controls".child_profile_id
        AND fl.parent_user_id = auth.uid()
    )
  );

CREATE POLICY "parent_controls_modify_linked_parent"
  ON "parent_controls" FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      JOIN public.family_links fl ON fl.child_user_id = p.user_id
      WHERE p.id = "parent_controls".child_profile_id
        AND fl.parent_user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      JOIN public.family_links fl ON fl.child_user_id = p.user_id
      WHERE p.id = "parent_controls".child_profile_id
        AND fl.parent_user_id = auth.uid()
    )
  );

-- Child can read their own controls (read-only — daily limit etc. is enforced server-side).
CREATE POLICY "parent_controls_select_child_self"
  ON "parent_controls" FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = "parent_controls".child_profile_id
        AND p.user_id = auth.uid()
    )
  );

-- ---- year_groups + subjects ----
-- Public reference data: readable by any authenticated user. Writes service-role only.
ALTER TABLE "year_groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "year_groups" FORCE ROW LEVEL SECURITY;
CREATE POLICY "year_groups_select_authenticated"
  ON "year_groups" FOR SELECT TO authenticated
  USING (true);

ALTER TABLE "subjects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subjects" FORCE ROW LEVEL SECURITY;
CREATE POLICY "subjects_select_authenticated"
  ON "subjects" FOR SELECT TO authenticated
  USING (true);

ALTER TABLE "zones" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "zones" FORCE ROW LEVEL SECURITY;
CREATE POLICY "zones_select_authenticated"
  ON "zones" FOR SELECT TO authenticated
  USING (true);

-- ---- Content tables: published-only reads ----
-- CLAUDE.md §8: every API/SQL path returning content to children MUST filter
-- status = 'published'. Enforced both in app code AND in RLS so a code-side
-- mistake can't leak staged/flagged content.
--
-- topics.is_published is the existing topic-level gate (boolean). Content rows
-- (learn_content / quiz_questions / card_catalog) carry the staged/published/
-- flagged/regenerating ContentStatus enum.

ALTER TABLE "topics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "topics" FORCE ROW LEVEL SECURITY;
CREATE POLICY "topics_select_published"
  ON "topics" FOR SELECT TO authenticated
  USING (is_published = true);

ALTER TABLE "learn_content" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "learn_content" FORCE ROW LEVEL SECURITY;
CREATE POLICY "learn_content_select_published"
  ON "learn_content" FOR SELECT TO authenticated
  USING (status = 'published');

ALTER TABLE "quiz_questions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "quiz_questions" FORCE ROW LEVEL SECURITY;
CREATE POLICY "quiz_questions_select_published"
  ON "quiz_questions" FOR SELECT TO authenticated
  USING (status = 'published');

ALTER TABLE "card_catalog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "card_catalog" FORCE ROW LEVEL SECURITY;
CREATE POLICY "card_catalog_select_published"
  ON "card_catalog" FOR SELECT TO authenticated
  USING (status = 'published');

-- ---- Gameplay tables: owner-only writes ----
-- CLAUDE.md §7 RLS baseline. Phases 5-7 wire the actual write paths; enabling
-- RLS now with self-only policies means a future API mistake can't write to
-- another child's row. Reads also self-only.

ALTER TABLE "topic_progress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "topic_progress" FORCE ROW LEVEL SECURITY;
CREATE POLICY "topic_progress_owner_all"
  ON "topic_progress" FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "topic_progress".profile_id AND p.user_id = auth.uid())
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "topic_progress".profile_id AND p.user_id = auth.uid())
  );

ALTER TABLE "quiz_attempts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "quiz_attempts" FORCE ROW LEVEL SECURITY;
CREATE POLICY "quiz_attempts_owner_all"
  ON "quiz_attempts" FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "quiz_attempts".profile_id AND p.user_id = auth.uid())
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "quiz_attempts".profile_id AND p.user_id = auth.uid())
  );

ALTER TABLE "quiz_answers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "quiz_answers" FORCE ROW LEVEL SECURITY;
CREATE POLICY "quiz_answers_owner_all"
  ON "quiz_answers" FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.quiz_attempts a
      JOIN public.profiles p ON p.id = a.profile_id
      WHERE a.id = "quiz_answers".attempt_id AND p.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.quiz_attempts a
      JOIN public.profiles p ON p.id = a.profile_id
      WHERE a.id = "quiz_answers".attempt_id AND p.user_id = auth.uid()
    )
  );

ALTER TABLE "session_answers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "session_answers" FORCE ROW LEVEL SECURITY;
CREATE POLICY "session_answers_owner_all"
  ON "session_answers" FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "session_answers".profile_id AND p.user_id = auth.uid())
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "session_answers".profile_id AND p.user_id = auth.uid())
  );

ALTER TABLE "point_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "point_events" FORCE ROW LEVEL SECURITY;
CREATE POLICY "point_events_owner_select"
  ON "point_events" FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "point_events".profile_id AND p.user_id = auth.uid())
  );

ALTER TABLE "child_collection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "child_collection" FORCE ROW LEVEL SECURITY;
CREATE POLICY "child_collection_owner_all"
  ON "child_collection" FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "child_collection".profile_id AND p.user_id = auth.uid())
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "child_collection".profile_id AND p.user_id = auth.uid())
  );

ALTER TABLE "profile_badges" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "profile_badges" FORCE ROW LEVEL SECURITY;
CREATE POLICY "profile_badges_owner_select"
  ON "profile_badges" FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "profile_badges".profile_id AND p.user_id = auth.uid())
  );

ALTER TABLE "streak_shields" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "streak_shields" FORCE ROW LEVEL SECURITY;
CREATE POLICY "streak_shields_owner_all"
  ON "streak_shields" FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "streak_shields".profile_id AND p.user_id = auth.uid())
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "streak_shields".profile_id AND p.user_id = auth.uid())
  );

ALTER TABLE "child_missions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "child_missions" FORCE ROW LEVEL SECURITY;
CREATE POLICY "child_missions_owner_all"
  ON "child_missions" FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "child_missions".profile_id AND p.user_id = auth.uid())
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = "child_missions".profile_id AND p.user_id = auth.uid())
  );

-- ---- Lookups + future-phase tables: fail-closed ----
-- RLS enabled with no policies so only service_role can read/write until the
-- relevant phase opens them up explicitly.

ALTER TABLE "world_map_nodes"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "world_map_nodes"      FORCE ROW LEVEL SECURITY;
CREATE POLICY "world_map_nodes_select_authenticated"
  ON "world_map_nodes" FOR SELECT TO authenticated
  USING (true);

ALTER TABLE "practice_games"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "practice_games"       FORCE ROW LEVEL SECURITY;
-- Practice games are gated by their parent topic.is_published — published-topic
-- policy at the topics level + service-role seeding keeps this safe in Phase 2.
CREATE POLICY "practice_games_select_via_published_topic"
  ON "practice_games" FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.topics t WHERE t.id = "practice_games".topic_id AND t.is_published = true)
  );

ALTER TABLE "badges"               ENABLE ROW LEVEL SECURITY;
ALTER TABLE "badges"               FORCE ROW LEVEL SECURITY;
CREATE POLICY "badges_select_authenticated"
  ON "badges" FOR SELECT TO authenticated
  USING (true);

ALTER TABLE "daily_challenges"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE "daily_challenges"     FORCE ROW LEVEL SECURITY;
-- Daily challenges cache question IDs that are themselves filtered by RLS on
-- quiz_questions; allow authenticated reads of the cache.
CREATE POLICY "daily_challenges_select_authenticated"
  ON "daily_challenges" FOR SELECT TO authenticated
  USING (true);

ALTER TABLE "past_paper_questions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "past_paper_questions" FORCE ROW LEVEL SECURITY;
-- No policies — Phase 2 deferred feature (CLAUDE.md §11). Service role only.

ALTER TABLE "curriculum_chunks"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE "curriculum_chunks"    FORCE ROW LEVEL SECURITY;
-- No policies — server-side RAG only. Children never read this table directly.
