import type { Metadata } from 'next'
import Link from 'next/link'
import { WorkedExample } from '@/components/reasoning/WorkedExample'
import { TOTAL_ITEMS } from '@/lib/reasoning/plan'
import { MAX_LEVEL, type Level, type ReasoningItemType } from '@/lib/reasoning/generate'
import { ReasoningRunner } from './ReasoningRunner'

// The test itself, and the page that has to rank for "non-verbal reasoning test".
//
// The test sits above the fold: making someone click through to the thing they
// came for loses most of them. Everything below it is the explanation, including
// one worked example of each question type — those anchors are what the report's
// practice links point at, so a parent who is told "practise matrices" lands on
// a matrix with the answer shown.

export const metadata: Metadata = {
  title: {
    absolute: 'Free Non-Verbal Reasoning Test: 24 Questions, Adaptive, No Account',
  },
  description:
    'Take a free adaptive non-verbal reasoning test. 24 shape puzzles across sequences, matrices, analogies and odd-one-out, with a worked example of every question type.',
  alternates: { canonical: '/reasoning/non-verbal' },
  openGraph: {
    title: 'Free Non-Verbal Reasoning Test | Decifer Learning',
    description:
      'Twenty-four adaptive shape puzzles, about twelve minutes, and a breakdown of how your child reasons.',
    url: 'https://www.deciferlearning.com/reasoning/non-verbal',
  },
}

export const revalidate = 3600

/**
 * The worked examples.
 *
 * Fixed seeds, so this page is stable: the same four puzzles every time, which
 * is what makes it cacheable, linkable and checkable. They are generated by the
 * same code that runs the test, so they cannot drift away from it.
 */
const EXAMPLES: {
  type: ReasoningItemType
  level: Level
  seed: string
  anchor: string
  heading: string
  body: string
  how: string
}[] = [
  {
    type: 'sequence',
    level: 3,
    seed: 'example-sequence',
    anchor: 'sequences',
    heading: 'Sequences',
    body: 'Five shapes in a row, with the last one missing. Something changes from each shape to the next, and the job is to say what and carry it on one more step.',
    how: 'Work through one property at a time: how many shapes, which shape, how it is filled, which way up. Name the change out loud before looking at the choices.',
  },
  {
    type: 'matrix',
    level: 3,
    seed: 'example-matrix',
    anchor: 'matrices',
    heading: 'Matrices',
    body: 'A three-by-three grid with the bottom-right square empty. One rule runs across the rows and a different rule runs down the columns, and the missing square obeys both.',
    how: 'Read across the top row first and work out that rule. Then read down the left column for the other one. Two easy questions beat one hard one.',
  },
  {
    type: 'analogy',
    level: 3,
    seed: 'example-analogy',
    anchor: 'analogies',
    heading: 'Analogies',
    body: 'The first shape becomes the second in some particular way. Do the same thing to the third shape.',
    how: 'Say the change as a sentence: "it got bigger and turned a quarter turn". Then do that sentence to the third shape before looking at the options.',
  },
  {
    type: 'odd_one_out',
    level: 3,
    seed: 'example-odd',
    anchor: 'odd-one-out',
    heading: 'Odd one out',
    body: 'Five shapes. Four of them share something and one does not. Find the one that breaks the pattern.',
    how: 'Check one property across all five before moving on to the next: all the shapes, then all the fills, then all the counts. Jumping between properties is how these get missed.',
  },
]

export default function NonVerbalPage() {
  return (
    <div className="space-y-8">
      <header className="space-y-3">
        <p className="font-mono text-xs uppercase tracking-wider text-ink-2">
          Free · no account · about 12 minutes
        </p>
        <h1 className="text-2xl font-bold text-ink sm:text-3xl">
          Free non-verbal reasoning test
        </h1>
        <p className="text-[15px] leading-relaxed text-ink-2">
          {TOTAL_ITEMS} shape puzzles, six of each of the four kinds below. It adapts as your
          child goes: a right answer makes the next one harder, a wrong one makes it easier, and
          there are {MAX_LEVEL} levels to climb. Hand them the screen and let them answer.
        </p>
      </header>

      <ReasoningRunner />

      <section className="space-y-3 rounded-2xl border border-black/5 bg-surface p-5">
        <h2 className="text-lg font-semibold text-ink">This test is visual</h2>
        <p className="text-[15px] leading-relaxed text-ink-2">
          Non-verbal reasoning means shapes, so a child needs to be able to see them. There is no
          version of &ldquo;which shape completes this pattern&rdquo; that does not. We have done
          what can be done: every shape carries a written description a screen reader reads out,
          the whole test works from a keyboard, and the shapes are filled with stripes, dots or
          solid black rather than colours, so nothing depends on telling colours apart. We would
          rather say this up front than have anyone find out the hard way.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-ink">The four kinds of puzzle</h2>
        <p className="text-[15px] leading-relaxed text-ink-2">
          One worked example of each, with the answer marked. These are made by the same code
          that makes the test, so they are exactly what your child will meet.
        </p>

        {EXAMPLES.map((ex) => (
          // scroll-mt keeps the heading clear of the top of the window when the
          // report's practice links jump straight to it.
          <section key={ex.anchor} id={ex.anchor} className="scroll-mt-20 space-y-3">
            <h3 className="text-lg font-semibold text-ink">{ex.heading}</h3>
            <p className="text-[15px] leading-relaxed text-ink-2">{ex.body}</p>
            <WorkedExample type={ex.type} level={ex.level} seed={ex.seed} />
            <p className="text-[15px] leading-relaxed text-ink-2">
              <strong className="text-ink">How to get better at these.</strong> {ex.how}
            </p>
          </section>
        ))}
      </section>

      <section className="space-y-3 rounded-2xl border border-ember/20 bg-brand-50 p-5">
        <h2 className="text-lg font-semibold text-ink">No IQ number, and why</h2>
        <p className="text-[15px] leading-relaxed text-ink-2">
          This measures the same kind of thinking an IQ test measures. It does not give an IQ
          score, a percentile, or any comparison with another child, because those only mean
          something when a test has first been given to a large, representative sample of
          children the same age. We have not done that, so a number would be invented. You get
          counts, levels and timings instead: facts about what happened.
        </p>
      </section>

      <nav className="flex flex-wrap gap-4 border-t border-black/5 pt-5">
        <Link
          href="/reasoning/cat4-practice"
          className="inline-flex min-h-[48px] items-center text-sm font-semibold text-ember hover:underline"
        >
          How this relates to the CAT4
        </Link>
        <Link
          href="/reasoning/11-plus"
          className="inline-flex min-h-[48px] items-center text-sm font-semibold text-ember hover:underline"
        >
          11+ non-verbal reasoning
        </Link>
      </nav>
    </div>
  )
}
