/** Animal Kingdom seed. Source: scripts/data/animals.json (Wikipedia CC BY-SA 4.0).
 *   node scripts/seed-animals.mjs --sql > /tmp/an.sql
 *   npx prisma db execute --url "$DATABASE_URL" --file /tmp/an.sql */
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const args = process.argv.slice(2)
const SQL_MODE = args.includes('--sql')
const PUBLISH = !args.includes('--unpublish')
const __dir = dirname(fileURLToPath(import.meta.url))
const ANIMALS = JSON.parse(readFileSync(join(__dir, 'data', 'animals.json'), 'utf8')).animals

const groups = []
for (const a of ANIMALS) if (!groups.find((g) => g.label === a.group)) groups.push({ key: a.group.toLowerCase(), label: a.group, color: a.color })

const EXPLORER = {
  key: 'animal-kingdom', title: 'Animal Kingdom', tagline: 'Meet species, explore habitats, discover wildlife',
  emoji: '🦁', scene_type: 'animal-grid',
  gradient: 'linear-gradient(135deg, #3e2723 0%, #5d4037 50%, #795548 100%)', order_index: 4,
  config: {
    background: '#0e0a08', groups,
    attribution: 'Animal summaries from Wikipedia (CC BY-SA 4.0).',
    completion: { title: 'Wildlife Explorer!', body: 'You met animals from across the planet.', points: 100 },
  },
}
const NODES = ANIMALS.map((a, i) => ({
  key: a.key, name: a.name, order_index: i,
  visual: { group: a.group, habitat: a.habitat, emoji: a.emoji, color: a.color },
  stats: {}, content: { kidFact: a.kidFact, summary: a.summary, source_url: a.source_url ?? null }, quiz: null,
}))

const sqlStr = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`)
const sqlJson = (v) => (v == null ? 'NULL' : `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`)

function emitSql() {
  const e = EXPLORER
  const lines = ['-- Generated by scripts/seed-animals.mjs --sql. Idempotent.', 'BEGIN;']
  lines.push('INSERT INTO explorers (key, title, tagline, emoji, scene_type, gradient, config, order_index, is_published, updated_at)')
  lines.push(`VALUES (${sqlStr(e.key)}, ${sqlStr(e.title)}, ${sqlStr(e.tagline)}, ${sqlStr(e.emoji)}, ${sqlStr(e.scene_type)}, ${sqlStr(e.gradient)}, ${sqlJson(e.config)}, ${e.order_index}, ${PUBLISH}, now())`)
  lines.push('ON CONFLICT (key) DO UPDATE SET title=EXCLUDED.title, tagline=EXCLUDED.tagline, emoji=EXCLUDED.emoji, scene_type=EXCLUDED.scene_type, gradient=EXCLUDED.gradient, config=EXCLUDED.config, order_index=EXCLUDED.order_index, is_published=EXCLUDED.is_published, updated_at=now();')
  lines.push(`DELETE FROM explorer_nodes WHERE explorer_id = (SELECT id FROM explorers WHERE key = ${sqlStr(e.key)});`)
  for (const n of NODES) {
    lines.push('INSERT INTO explorer_nodes (explorer_id, key, name, order_index, visual, stats, content, quiz)')
    lines.push(`VALUES ((SELECT id FROM explorers WHERE key = ${sqlStr(e.key)}), ${sqlStr(n.key)}, ${sqlStr(n.name)}, ${n.order_index}, ${sqlJson(n.visual)}, ${sqlJson(n.stats)}, ${sqlJson(n.content)}, ${sqlJson(n.quiz)});`)
  }
  lines.push('COMMIT;'); console.log(lines.join('\n'))
}

async function main() {
  if (SQL_MODE) { emitSql(); return }
  const { createClient } = await import('@supabase/supabase-js')
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL, key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) { console.error('Missing env; use --sql.'); process.exit(1) }
  const supabase = createClient(url, key, { auth: { persistSession: false } })
  const { data: ex, error } = await supabase.from('explorers').upsert({ key: EXPLORER.key, title: EXPLORER.title, tagline: EXPLORER.tagline, emoji: EXPLORER.emoji, scene_type: EXPLORER.scene_type, gradient: EXPLORER.gradient, config: EXPLORER.config, order_index: EXPLORER.order_index, is_published: PUBLISH, updated_at: new Date().toISOString() }, { onConflict: 'key' }).select('id').single()
  if (error) throw error
  await supabase.from('explorer_nodes').delete().eq('explorer_id', ex.id)
  const { error: insErr } = await supabase.from('explorer_nodes').insert(NODES.map((n) => ({ explorer_id: ex.id, ...n })))
  if (insErr) throw insErr
  console.log(`✓ Seeded animal-kingdom with ${NODES.length} animals.`)
}
main().catch((e) => { console.error('Seed failed:', e.message ?? e); process.exit(1) })
